/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package admin;

import classes.ProfessorDirectory;
import classes.StudentDirectory;
import java.awt.CardLayout;
import java.awt.Component;
import javax.swing.DefaultListCellRenderer;
import javax.swing.DefaultListModel;
import javax.swing.JLabel;
import javax.swing.JList;
import javax.swing.JPanel;



/**
 *
 * @author visho
 */
public class adminHomepageJPanel extends javax.swing.JPanel {
private JPanel workareaContainer;
private StudentDirectory studentdir;
private ProfessorDirectory profdir;

/**
     * Creates new form adminHomepageJPanel
     */

   
// Define the list model
private DefaultListModel<String> listModel;

// Constructor
public adminHomepageJPanel(JPanel workareaContainer, StudentDirectory studentdir, ProfessorDirectory profdir) {
        this.workareaContainer = workareaContainer;
        this.studentdir = studentdir;
        this.profdir = profdir;
        initComponents();

        // Initialize the list model
        listModel = new DefaultListModel<>();
        jList1.setModel(listModel); // Set the listModel for your JList

        // Set the cell renderer using an anonymous inner class
        jList1.setCellRenderer(new DefaultListCellRenderer() {
            @Override
            public Component getListCellRendererComponent(JList<?> list, Object value, int index, boolean isSelected, boolean cellHasFocus) {
                Component renderer = super.getListCellRendererComponent(list, value, index, isSelected, cellHasFocus);
                if (renderer instanceof JLabel) {
                    JLabel label = (JLabel) renderer;
                    label.setText("<html>" + value.toString() + "</html>");
                    label.setToolTipText(value.toString()); // This sets the tooltip with the full text
                }
                return renderer;
            }
        });

        // Populate the list with Noticeboard data
        populateList();
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        manageStudent = new javax.swing.JButton();
        manageFaculty = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        displayStudent = new javax.swing.JButton();
        displayProfessor = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList<>();
        jLabel2 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 232, 173));

        manageStudent.setBackground(new java.awt.Color(153, 153, 153));
        manageStudent.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        manageStudent.setForeground(new java.awt.Color(0, 0, 0));
        manageStudent.setText("Manage Student");
        manageStudent.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 153, 51), 5));
        manageStudent.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                manageStudentActionPerformed(evt);
            }
        });

        manageFaculty.setBackground(new java.awt.Color(153, 153, 153));
        manageFaculty.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        manageFaculty.setForeground(new java.awt.Color(0, 0, 0));
        manageFaculty.setText("Manage Faculty");
        manageFaculty.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 153, 51), 5));
        manageFaculty.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                manageFacultyActionPerformed(evt);
            }
        });

        jLabel1.setBackground(new java.awt.Color(204, 204, 204));
        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("WELCOME ADMIN");

        displayStudent.setBackground(new java.awt.Color(153, 153, 153));
        displayStudent.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        displayStudent.setForeground(new java.awt.Color(0, 0, 0));
        displayStudent.setText("Display Students");
        displayStudent.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 153, 51), 5));
        displayStudent.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                displayStudentActionPerformed(evt);
            }
        });

        displayProfessor.setBackground(new java.awt.Color(153, 153, 153));
        displayProfessor.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        displayProfessor.setForeground(new java.awt.Color(0, 0, 0));
        displayProfessor.setText("Display Professors");
        displayProfessor.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 153, 51), 5));
        displayProfessor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                displayProfessorActionPerformed(evt);
            }
        });

        jList1.setLayoutOrientation(javax.swing.JList.VERTICAL_WRAP);
        jScrollPane2.setViewportView(jList1);

        jLabel2.setBackground(new java.awt.Color(153, 153, 153));
        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("USER MANAGEMENT");
        jLabel2.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 153, 0), 5, true));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(329, 329, 329)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(manageFaculty, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(manageStudent, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(displayProfessor, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(displayStudent, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 355, Short.MAX_VALUE)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 301, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(15, 15, 15))
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {displayProfessor, displayStudent, jLabel2, manageFaculty, manageStudent});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(128, 128, 128)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 268, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(32, 32, 32)
                                .addComponent(displayStudent, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(12, 12, 12)
                                .addComponent(displayProfessor, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(manageStudent, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(manageFaculty, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(222, Short.MAX_VALUE))
        );

        layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {displayProfessor, displayStudent, jLabel2, manageFaculty, manageStudent});

    }// </editor-fold>//GEN-END:initComponents

    private void manageStudentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_manageStudentActionPerformed
        // TODO add your handling code here:
        ManageStudent manageStudent = new ManageStudent(workareaContainer, studentdir);
        workareaContainer.add(manageStudent);
        ((CardLayout) workareaContainer.getLayout()).next(workareaContainer);
    }//GEN-LAST:event_manageStudentActionPerformed

    private void manageFacultyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_manageFacultyActionPerformed
        // TODO add your handling code here:
        ManageProfessor manageFaculty = new ManageProfessor(workareaContainer, profdir);
        workareaContainer.add("ManageFaculty", manageFaculty);
        ((CardLayout) workareaContainer.getLayout()).next(workareaContainer);
    }//GEN-LAST:event_manageFacultyActionPerformed

    private void displayStudentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_displayStudentActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_displayStudentActionPerformed

    private void displayProfessorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_displayProfessorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_displayProfessorActionPerformed

    private void populateList() {
        // Clear the list model
        listModel.clear();

        // Add rows of information to the list
        listModel.addElement("10/10/2023 - Kal Bug - Java Expert - Specializes in teaching Java programming, guiding students through the ins and outs of this versatile language");
        listModel.addElement("11/10/2023 - Vishal Chawla - Web Tools Wizard - Equips students with the knowledge and skills needed for mastering various web tools and technologies");
        // Add more notices as needed
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton displayProfessor;
    private javax.swing.JButton displayStudent;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JList<String> jList1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JButton manageFaculty;
    private javax.swing.JButton manageStudent;
    // End of variables declaration//GEN-END:variables
}
