/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package student;

/**
 *
 * @author visho
 */
public class ProfFeedbackJPanel extends javax.swing.JPanel {

    /**
     * Creates new form ProfRIJPanel
     */
    public ProfFeedbackJPanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        label = new javax.swing.JLabel();
        lblprof1 = new javax.swing.JLabel();
        lblprof2 = new javax.swing.JLabel();
        lblprof3 = new javax.swing.JLabel();
        lblprof4 = new javax.swing.JLabel();
        lblprof5 = new javax.swing.JLabel();
        lblprof6 = new javax.swing.JLabel();
        lblprof7 = new javax.swing.JLabel();
        lblprof8 = new javax.swing.JLabel();

        label.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        label.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        label.setText("Provide feedback for your professor");

        lblprof1.setText("Prof7");

        lblprof2.setText("Prof1");

        lblprof3.setText("Prof2");

        lblprof4.setText("Prof3");

        lblprof5.setText("Prof4");

        lblprof6.setText("Prof5");

        lblprof7.setText("Prof6");

        lblprof8.setText("Prof8");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(243, 243, 243)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblprof1)
                    .addComponent(lblprof2)
                    .addComponent(lblprof3)
                    .addComponent(lblprof4)
                    .addComponent(lblprof5)
                    .addComponent(lblprof6)
                    .addComponent(lblprof7)
                    .addComponent(lblprof8))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(284, Short.MAX_VALUE)
                .addComponent(label)
                .addGap(208, 208, 208))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(label)
                .addGap(62, 62, 62)
                .addComponent(lblprof1)
                .addGap(18, 18, 18)
                .addComponent(lblprof2)
                .addGap(18, 18, 18)
                .addComponent(lblprof3)
                .addGap(18, 18, 18)
                .addComponent(lblprof4)
                .addGap(18, 18, 18)
                .addComponent(lblprof5)
                .addGap(18, 18, 18)
                .addComponent(lblprof6)
                .addGap(18, 18, 18)
                .addComponent(lblprof7)
                .addGap(18, 18, 18)
                .addComponent(lblprof8)
                .addContainerGap(246, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel label;
    public javax.swing.JLabel lblprof1;
    public javax.swing.JLabel lblprof2;
    public javax.swing.JLabel lblprof3;
    public javax.swing.JLabel lblprof4;
    public javax.swing.JLabel lblprof5;
    public javax.swing.JLabel lblprof6;
    public javax.swing.JLabel lblprof7;
    public javax.swing.JLabel lblprof8;
    // End of variables declaration//GEN-END:variables
}
